version: '3.9'

services:
  filmes-api:
    build:
      context: ./FilmesApi
    ports:
      - "5000:80"
    networks:
      - filmes-net

  filmes-front:
    build:
      context: ./filmes-front
    ports:
      - "4200:80"
    networks:
      - filmes-net
    depends_on:
      - filmes-api

networks:
  filmes-net:
