version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_filmes
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: filme
    volumes:
      - db_filmes:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - filmes-net

  api:
    image: renanmunizdev/filmes-api:latest
    container_name: filmes-api
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__FilmeConnection=server=mysql;port=3306;database=filme;user=root;password=root
    networks:
      - filmes-net

  front:
    image: renanmunizdev/filmes-front:latest
    container_name: filmes-front
    restart: always
    depends_on:
      - api
    ports:
      - "4200:80"
    networks:
      - filmes-net

volumes:
  db_filmes:

networks:
  filmes-net:
