name: CI/CD Projeto Filmes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configura Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build da API (.NET)
      run: |
        docker build -t filmes-api ./FilmesApi

    - name: Build do Frontend (Angular)
      run: |
        docker build -t filmes-front -f ./filmes-front/Dockerfile ./filmes-front

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push imagem da API
      run: |
        docker tag filmes-api renanmunizdev/filmes-api:latest
        docker push renanmunizdev/filmes-api:latest

    - name: Push imagem do Frontend
      run: |
        docker tag filmes-front renanmunizdev/filmes-front:latest
        docker push renanmunizdev/filmes-front:latest
